server:
  port: 9040
spring:
  profiles:
    active: dev
    include: common,data
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 5MB
dubbo:
  application:
    qos-port: 22260

novel:
  file:
    # 文件上传配置
    upload:
      # 上传路径
      path: D:/Code/JavaCode/rayc-novel/upload

management:
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-resource-service.log