server:
  port: 9020
spring:
  profiles:
    active: dev
    include: common,data
dubbo:
  application:
    qos-port: 22220
  protocol:
    name: dubbo
    port: 20820

management:
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-book-service.log